version: '3'

services:
  cypress:
    build: .
    volumes:
      - ./cypress:/e2e/cypress
      - ./cypress.config.js:/e2e/cypress.config.js
      - ./package.json:/e2e/package.json
      - ./package-lock.json:/e2e/package-lock.json
      - ./cypress.env.json:/e2e/cypress.env.json
    environment:
      - CYPRESS_BASE_URL=https://app.pipedrive.com
      - CYPRESS_EMAIL=${CYPRESS_EMAIL}
      - CYPRESS_PASSWORD=${CYPRESS_PASSWORD}
    command: npx cypress run 