name: Cypress E2E Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'

      - name: List workspace contents (pre-test)
        run: |
          pwd
          ls -la
          npm -v
          node -v

      - name: Install dependencies
        run: npm ci

      - name: Create reports directory
        run: |
          mkdir -p cypress/reports/mochawesome
          mkdir -p cypress/reports/mochawesome/.jsons
          mkdir -p cypress/screenshots
          mkdir -p cypress/videos

      - name: Run Cypress tests
        run: npm run test:chrome
        continue-on-error: true
        env:
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
          CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}

      - name: Generate Mochawesome report
        if: always()
        run: |
          npm run merge:reports || echo "Failed to merge reports"
          npm run generate:report || echo "Failed to generate report"

      - name: List workspace contents (post-test)
        if: always()
        run: |
          echo "Current directory:"
          pwd
          echo "Cypress directory structure:"
          find cypress -type d
          echo "Files in cypress/reports/mochawesome:"
          ls -la cypress/reports/mochawesome || echo "No mochawesome directory"
          echo "Files in cypress/screenshots:"
          ls -la cypress/screenshots || echo "No screenshots"
          echo "Files in cypress/videos:"
          ls -la cypress/videos || echo "No videos"

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-report
          path: cypress/reports/mochawesome
          if-no-files-found: warn

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: cypress/screenshots
          if-no-files-found: warn

      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: videos
          path: cypress/videos
          if-no-files-found: warn 