name: Cypress E2E Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create reports directory
        run: |
          mkdir -p cypress/reports/mochawesome
          mkdir -p cypress/reports/mochawesome/.jsons
          mkdir -p cypress/screenshots
          mkdir -p cypress/videos
          chmod -R 777 cypress

      - name: Run Cypress tests
        run: npm run test:chrome
        continue-on-error: true
        env:
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
          CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}

      - name: Generate Mochawesome report
        if: always()
        run: |
          npm run merge:reports || echo "Failed to merge reports"
          npm run generate:report || echo "Failed to generate report"

      - name: List workspace contents (post-test)
        if: always()
        run: |
          echo "Current directory structure:"
          tree cypress || find cypress -type d
          echo -e "\nFile permissions in cypress directory:"
          ls -lR cypress

      - name: Prepare artifacts
        if: always()
        run: |
          # Create a single directory for all artifacts
          mkdir -p artifact_upload
          # Copy only if they exist and have content
          [ -d "cypress/reports/mochawesome" ] && cp -r cypress/reports/mochawesome artifact_upload/ || echo "No mochawesome reports"
          [ -d "cypress/screenshots" ] && cp -r cypress/screenshots artifact_upload/ || echo "No screenshots"
          [ -d "cypress/videos" ] && cp -r cypress/videos artifact_upload/ || echo "No videos"
          echo "Contents of artifact_upload directory:"
          ls -lR artifact_upload

      - name: Upload all artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: artifact_upload
          retention-days: 5
          if-no-files-found: warn 