name: Cypress E2E Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'

      - name: List workspace contents (pre-test)
        run: |
          pwd
          ls -la
          npm -v
          node -v

      - name: Install dependencies
        run: npm ci

      - name: Create reports directory
        run: |
          mkdir -p cypress/reports/mochawesome
          mkdir -p cypress/reports/mochawesome/.jsons

      - name: Run Cypress tests
        run: npm run test:chrome
        continue-on-error: true

      - name: Generate Mochawesome report
        if: always()
        run: |
          npm run merge:reports
          npm run generate:report

      - name: List workspace contents (post-test)
        if: always()
        run: |
          pwd
          ls -la cypress || echo "No cypress directory"
          ls -la cypress/screenshots || echo "No screenshots directory"
          ls -la cypress/videos || echo "No videos directory"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            cypress/reports/mochawesome
            cypress/screenshots
            cypress/videos
          if-no-files-found: warn 