name: Cypress E2E Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  cypress-run:
    name: Cypress Tests
    runs-on: ubuntu-latest
    container:
      image: cypress
      