name: Cypress E2E Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Build Docker image
        run: docker build -t cypress-automation .

      - name: Create reports directory
        run: |
          mkdir -p cypress/reports/mochawesome
          mkdir -p cypress/reports/mochawesome/.jsons
          mkdir -p cypress/screenshots
          mkdir -p cypress/videos
          chmod -R 777 cypress

      - name: Run Cypress tests in Docker container
        run: |
          docker run --rm -v "${PWD}:/e2e" -w /e2e -e CYPRESS_BASE_URL=${{ secrets.CYPRESS_BASE_URL }} \
          -e CYPRESS_EMAIL=${{ secrets.CYPRESS_EMAIL }} -e CYPRESS_PASSWORD=${{ secrets.CYPRESS_PASSWORD }} \
          cypress-automation npm run test:chrome
        continue-on-error: true

      - name: Generate Mochawesome report
        if: always()
        run: |
          docker run --rm -v "${PWD}:/e2e" -w /e2e cypress-automation npm run generate:all-reports

      - name: Upload Mochawesome Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/mochawesome
          retention-days: 5

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 5

      - name: Upload Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 5
