name: Cypress E2E Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
            
      - name: Install dependencies
        run: |
          npm ci
          npm install -g mochawesome-merge mochawesome-report-generator
          npm list -g --depth=0
        
      - name: Create and set permissions
        run: |
          echo "Creating directories..."
          mkdir -p cypress/reports/mochawesome
          mkdir -p cypress/reports/mochawesome/.jsons
          mkdir -p cypress/screenshots
          mkdir -p cypress/videos
          mkdir -p cypress/downloads
          echo "Setting permissions..."
          sudo chown -R $USER:$USER cypress
          chmod -R 777 cypress
          echo "Verifying permissions..."
          ls -la cypress
          ls -la cypress/downloads
        
      - name: Run Cypress tests in Docker
        run: |
          echo "Running Cypress tests in Docker..."
          docker run --rm \
            -v "${PWD}:/e2e" \
            -w /e2e \
            -e CYPRESS_BASE_URL=${{ secrets.CYPRESS_BASE_URL }} \
            -e CYPRESS_EMAIL=${{ secrets.CYPRESS_EMAIL }} \
            -e CYPRESS_PASSWORD=${{ secrets.CYPRESS_PASSWORD }} \
            cypress/included:12.17.4 \
            --config reporter=cypress-mochawesome-reporter \
            --config reporterOptions.reportDir=cypress/reports/mochawesome \
            --config reporterOptions.overwrite=false \
            --config reporterOptions.html=false \
            --config reporterOptions.json=true \
            --browser chrome
        continue-on-error: true
        
      - name: Generate Mochawesome report
        if: always()
        run: |
          echo "Current directory structure:"
          sudo find cypress -type d
          echo -e "\nGenerating reports..."
          # Ensure .jsons directory exists
          mkdir -p cypress/reports/mochawesome/.jsons
          chmod 777 cypress/reports/mochawesome/.jsons
          
          if [ -z "$(ls -A cypress/reports/mochawesome/.jsons/*.json 2>/dev/null)" ]; then
            echo 'No test reports found, creating dummy report...'
            echo '{"stats":{"suites":1,"tests":1,"passes":0,"pending":0,"failures":0,"start":"2024-01-01T00:00:00.000Z","end":"2024-01-01T00:00:00.000Z","duration":0},"results":[{"uuid":"dummy-test","title":"No tests executed","fullFile":"dummy.js","file":"dummy.js","beforeHooks":[],"afterHooks":[],"tests":[{"title":"No tests executed","fullTitle":"No tests executed","timedOut":false,"duration":0,"state":"skipped","speed":"fast","pass":true,"fail":false,"pending":false,"context":null,"code":"","err":{},"uuid":"dummy-test-1","parentUUID":"dummy-test","isHook":false,"skipped":true}],"suites":[],"passes":[],"failures":[],"pending":[],"skipped":["No tests executed"],"duration":0,"root":true,"rootEmpty":true,"_timeout":2000}]}' > cypress/reports/mochawesome/.jsons/dummy.json
            chmod 666 cypress/reports/mochawesome/.jsons/dummy.json
          fi
          
          echo "Merging reports..."
          npx mochawesome-merge cypress/reports/mochawesome/.jsons/*.json > cypress/reports/mochawesome/merged.json
          chmod 666 cypress/reports/mochawesome/merged.json
          
          echo "Generating HTML report..."
          npx marge cypress/reports/mochawesome/merged.json -f report -o cypress/reports/mochawesome
          
          echo -e "\nReport directory contents:"
          ls -R cypress/reports/mochawesome

      - name: Upload Mochawesome Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/mochawesome
          retention-days: 5

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 5

      - name: Upload Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 5
