name: Cypress E2E Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  cypress-run:
    name: Cypress Tests
    runs-on: ubuntu-latest
    container:
      image: cypress/included:14.3.2
      options: >
        --user 1001
        -v "${{ github.workspace }}:/e2e"
        -w "/e2e"
    timeout-minutes: 30
    env:
      CYPRESS_RETRIES: 2
      CYPRESS_VIDEO: true
      CYPRESS_SCREENSHOTS: true
      DISPLAY: :99
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug environment
        run: |
          echo "Current user: $(whoami)"
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "Cypress version: $(npx cypress --version)"
          echo "Docker info:"
          docker info

      - name: Install dependencies
        run: |
          npm ci
          npm cache verify

      - name: Setup test environment
        run: |
          mkdir -p cypress/reports/mochawesome/.jsons
          mkdir -p cypress/screenshots
          mkdir -p cypress/videos
          chmod -R 777 cypress

      - name: Clean previous reports
        run: npm run clean:reports

      - name: Run Cypress tests
        run: |
          echo "Starting Cypress tests..."
          echo "Test files to run:"
          find cypress/e2e -name "*.cy.js"
          npm run test:chrome
        continue-on-error: true
        env:
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
          CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}

      - name: Generate Mochawesome report
        if: always()
        run: |
          echo "Generating reports..."
          npm run merge:reports || echo "Failed to merge reports"
          npm run generate:report || echo "Failed to generate report"
          echo "Report directory contents:"
          ls -R cypress/reports/mochawesome

      - name: Upload Mochawesome Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/mochawesome
          retention-days: 5

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 5

      - name: Upload Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 5
