name: Cypress Tests

on:
  push:
    branches: [ main, master, test ]
  pull_request:
    branches: [ main, master, test ]
  workflow_dispatch:

jobs:
  cypress-run:
    name: Cypress Tests
    runs-on: ubuntu-latest
    container:
      image: cypress/included:latest
      options: --user 1001
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          # Install system dependencies required for Cypress
          apt-get update && apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: Create reports directory
        run: |
          mkdir -p cypress/reports/mochawesome/.jsons
          mkdir -p cypress/screenshots
          mkdir -p cypress/videos
          chmod -R 777 cypress

      - name: Run Cypress tests
        env:
          CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_BASE_URL: https://app.pipedrive.com
        run: |
          npx cypress run --config video=true,screenshotOnRunFailure=true,trashAssetsBeforeRuns=false

      - name: Generate Mochawesome report
        if: always()
        run: |
          echo "Current directory structure:"
          find cypress -type d
          echo -e "\nGenerating reports..."
          
          # Ensure .jsons directory exists
          mkdir -p cypress/reports/mochawesome/.jsons
          
          # Move any JSON files to .jsons directory if they're not already there
          find cypress/reports/mochawesome -maxdepth 1 -name "*.json" -exec mv {} cypress/reports/mochawesome/.jsons/ \;
          
          # Check if we have any JSON files
          if [ -z "$(find cypress/reports/mochawesome/.jsons/ -name '*.json')" ]; then
            echo "No reports found to merge."
            # Create a properly formatted dummy JSON file with all required fields
            echo '{
              "stats": {
                "suites": 0,
                "tests": 0,
                "passes": 0,
                "pending": 0,
                "failures": 0,
                "start": "2024-04-29T00:00:00.000Z",
                "end": "2024-04-29T00:00:00.000Z",
                "duration": 0,
                "passPercent": 0,
                "pendingPercent": 0,
                "other": 0,
                "hasOther": false,
                "skipped": 0,
                "hasSkipped": false
              },
              "results": [],
              "meta": {
                "mocha": {
                  "version": "10.2.0"
                },
                "mochawesome": {
                  "options": {
                    "quiet": false,
                    "reportFilename": "mochawesome",
                    "reportDir": "cypress/reports/mochawesome",
                    "reportTitle": "Cypress Test Report",
                    "reportPageTitle": "Cypress Test Report",
                    "timestamp": "2024-04-29T00:00:00.000Z"
                  },
                  "version": "10.2.0"
                },
                "marge": {
                  "options": {
                    "reportDir": "cypress/reports/mochawesome",
                    "reportFilename": "report",
                    "reportTitle": "Cypress Test Report",
                    "reportPageTitle": "Cypress Test Report",
                    "timestamp": "2024-04-29T00:00:00.000Z",
                    "charts": true,
                    "code": true,
                    "autoOpen": false,
                    "overwrite": false,
                    "cdn": true,
                    "saveJson": true,
                    "saveHtml": true,
                    "saveAllVideos": true,
                    "inline": true,
                    "quiet": false
                  },
                  "version": "6.2.0"
                }
              }
            }' > cypress/reports/mochawesome/.jsons/dummy.json
          fi
          
          # Generate the report
          echo "Merging reports..."
          npm run merge:reports
          echo "Generating final report..."
          npm run generate:report
          
          echo -e "\nReport directory contents:"
          ls -R cypress/reports/mochawesome

      - name: Upload Mochawesome Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/mochawesome
          retention-days: 5
          if-no-files-found: warn

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 5
          if-no-files-found: warn

      - name: Upload Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 5
          if-no-files-found: warn 