name: Cypress CI - Core Tests

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  cypress-tests:
    name: Cypress Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          ~/.cache/Cypress
        key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-cypress-

    - name: Install dependencies
      run: npm ci

    - name: Verify Cypress
      run: npx cypress verify

    - name: Run headless tests (default)
      uses: cypress-io/github-action@v6
      with:
        command: npm run triggerAllTests-headless

    - name: Run headed tests (with GUI)
      uses: cypress-io/github-action@v6
      with:
        command: npm run triggerAllTests-headed
        headed: true
      continue-on-error: true  # Headed tests may fail in CI environment

    - name: Run Chrome tests
      uses: cypress-io/github-action@v6
      with:
        command: npm run triggerAllTests-chrome
        browser: chrome

    - name: Store test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cypress-results
        path: |
          cypress/videos/**
          cypress/screenshots/**
        retention-days: 3