name: Test Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker --version
          docker-compose --version

      - name: Test Docker Build
        run: |
          docker build -t cypress-test .
          docker images | grep cypress-test

      - name: Test Docker Run
        run: |
          docker run --rm cypress-test npx cypress --version 